// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI8r6bwGHjJ2O7qcymkeLNKkPpYJwfLgQ',
    appId: '1:204365509817:web:7f0424467c17cd221f9768',
    messagingSenderId: '204365509817',
    projectId: 'easyshopping-b3d75',
    authDomain: 'easyshopping-b3d75.firebaseapp.com',
    storageBucket: 'easyshopping-b3d75.appspot.com',
    measurementId: 'G-E05Y144RPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6iLO26FU08i0zM2ugOjojqcbrOslVFW8',
    appId: '1:204365509817:android:a86ce0eb0e26a9bd1f9768',
    messagingSenderId: '204365509817',
    projectId: 'easyshopping-b3d75',
    storageBucket: 'easyshopping-b3d75.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8juJ7jlhCBvH_E3MU3vegJ159TpHt9uI',
    appId: '1:204365509817:ios:645b6941e3baf4d51f9768',
    messagingSenderId: '204365509817',
    projectId: 'easyshopping-b3d75',
    storageBucket: 'easyshopping-b3d75.appspot.com',
    iosBundleId: 'com.example.eCom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8juJ7jlhCBvH_E3MU3vegJ159TpHt9uI',
    appId: '1:204365509817:ios:645b6941e3baf4d51f9768',
    messagingSenderId: '204365509817',
    projectId: 'easyshopping-b3d75',
    storageBucket: 'easyshopping-b3d75.appspot.com',
    iosBundleId: 'com.example.eCom',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDI8r6bwGHjJ2O7qcymkeLNKkPpYJwfLgQ',
    appId: '1:204365509817:web:683d333adafd915e1f9768',
    messagingSenderId: '204365509817',
    projectId: 'easyshopping-b3d75',
    authDomain: 'easyshopping-b3d75.firebaseapp.com',
    storageBucket: 'easyshopping-b3d75.appspot.com',
    measurementId: 'G-4KMXTCSDF9',
  );
}
